package backend.healthdatamodule.rules;

import backend.healthdatamodule.dto.BurnoutInput;

// pravilo za nizak rizik
// opis: ako su radni sati <= 40 I nivo stresa <= 5
rule "Low risk"
    when
        $input : BurnoutInput(workingHours <= 40, stressLevel <= 5)
    then
        System.out.println("Rule 'Low risk' activated.");
        $input.setRiskLevel("low");
        $input.setRecommendation("Recommendation: Continue monitoring and take micro-breaks.");
end

// pravilo za srednji rizik
// opis: ako su radni sati izmedju 41 i 50 ILI nivo stresa izmedju 6 i 7
rule "Medium risk"
    when
        $input : BurnoutInput( (workingHours >= 41 && workingHours <= 50) || (stressLevel >= 6 && stressLevel <= 7) )
    then
        System.out.println("Rule 'Medium risk' activated.");
        $input.setRiskLevel("medium");
        $input.setRecommendation("Recommendation: Short leave (1-2 days) and a conversation with HR.");
end

// pravilo za visok rizik
// opis: ako su radni sati > 50 I nivo stresa >= 8 I sati sna < 6
rule "High risk"
    when
        $input : BurnoutInput(workingHours > 50, stressLevel >= 8, sleepHours < 6)
    then
        System.out.println("Rule 'High risk' activated.");
        $input.setRiskLevel("high");
        $input.setRecommendation("URGENT: Suggest leave and notify the manager about increased burnout risk.");
end
