package backend.healthdatamodule.drools;

import backend.healthdatamodule.facts.WeeklyReport;

rule "Increase risk if average working hours > 48"
when
    $report: WeeklyReport(avgWorkingHours > 48)
then
    int oldRisk = $report.getRiskLevel();
    $report.setRiskLevel(oldRisk + 1);
    $report.getRecommendations().add("Prosečan broj radnih sati poslednje 4 nedelje veći od 48 – povećan rizik.");
    update($report);
end

rule "Increase risk if stress increased ≥ 2 in 3 weeks"
when
    $report: WeeklyReport(stressIncreaseLast3Weeks >= 2)
then
    int oldRisk = $report.getRiskLevel();
    $report.setRiskLevel(oldRisk + 1);
    $report.getRecommendations().add("Samoprocena stresa rasla ≥ 2 poena tokom 3 nedelje – povećan rizik.");
    update($report);
end

rule "Overtime increase 3 consecutive weeks"
when
    $report: WeeklyReport(overtimeIncreaseStreak >= 3)
then
    $report.getRecommendations().add("Broj prekovremenih sati povećan 3 uzastopne nedelje – razmotrite korekciju radnih obaveza.");
    update($report);
end
