package rules.weekly;

global burnoutrulesengine.burnoutrulesengine.model.BurnoutRisk riskResult;

import burnoutrulesengine.burnoutrulesengine.model.WeeklyRecordFact;

rule "Moderate Weekly Burnout Risk"
when
    $f: WeeklyRecordFact(avgWorkingHours > 8, avgStressLevel >= 6, avgSleepHours < 6)
then
    if (riskResult.getRiskLevel() == null) {
        riskResult.setRiskLevel("Srednji");
        riskResult.setRecommendation("Umeren nivo stresa. Preporučuje se kraći odmor i balans između posla i sna.");
        riskResult.setManagerNotificationNeeded(false);
        System.out.println("⚠️ Aktivirano pravilo: Moderate Weekly Burnout Risk");
    }
end
